In [1]:
import math
from numpy import array as matrix
from numpy.linalg import inv
from numpy import transpose
from numpy.linalg import det
from numpy import roots
from numpy import arange
from numpy import linspace
import matplotlib.pyplot as plt

#cw. 1
k = 1240 * math.sqrt(7)
m = 4467
l = 2j
d = k + m
c = d + l

print("cw.1\nk =", k, type(k))
print ("m =", m, type(m))
print ("l =", l, type(l))
print ("d =", k + m, type(k+m))
print ("c =", d + l, type(d+l))

#cw. 2
print ("\ncw.2\nd(3) =", ("%.3f" % d))
print ("d(15) =", ("%.15f" % d))


#cw. 3
r = 17
h = 33
print ("\ncw.3\nS =", 2 * math.pi * r**2 + 2 * math.pi * r * h)

#cw. 5
def B(x, r, t):
    return ((x + r)/(r * math.sin(2 * x) + 3.3456))*x**(t*r)

print ("\ncw.5\nB =", B(1,2,3))

#cw. 6
a = math.sqrt(2)
M = matrix([[a, 1, -a], [0, 1, 1], [-a, a, 1]])
Minv = inv(M)
Mt = transpose(M)
Mdet = det(M)

print ("\ncw.6\nM:\n {0}".format(M))
print ("Minv:\n {0}".format(Minv))
print ("Mt:\n {0}".format(Mt))
print ("Mdet =", Mdet)

#cw. 7

print ("\ncw.7\n M(1,1) = {0}".format(M[0,0]))
print ("M(3,3) = {0}".format(M[2,2]))
print ("M(3,2) = {0}".format(M[2,1]))

w1 = matrix(M[:,2])
w2 = matrix(M[1,:])
print("w1:\n {0}".format(w1))
print("w2:\n {0}".format(w2))

#cw. 8
coeff = [1, -7, 3, 43, -28, -60]
print("\ncw.8\nPierwiastki: ",roots(coeff))


def check(x):
    return x*( x*( x*( x*( x - 7 )+ 3 ) + 43 ) - 28 ) - 60

print("\nSprawdzenie wartosci {0}".format([check(x) for x in roots(coeff)]))

#cw. 9
print("\ncw.9\n",arange(0,5,1.0/2))
print (linspace(0,4.5,10))

#cw. 10

def f(x):
    return x**3-3*x

x1 = linspace(-1,1)
y1 = f(x1)
plt.plot(x1, y1)
plt.title('Wykres 1')
plt.xlabel('x')
plt.ylabel('y')
plt.legend('Wykres 1')
plt.show()

x2 = linspace(-5,5)
y2 = f(x2)
plt.plot(x2,y2)
plt.title('Wykres 2')
plt.xlabel('x')
plt.ylabel('y')
plt.legend('Wykres 2')
plt.show()

x3 = linspace(0,5)
y3 = f(x3)
plt.plot(x3,y3)
plt.title('Wykres 3')
plt.xlabel('x')
plt.ylabel('y')
plt.legend('Wykres 3')
plt.show()


#cw 11

def heat(m, v):
    return (m*pow(v,2))/2

print("\ncw.11\nCiepło dla m=2.5kg, v=60km/h =", heat(2.5, 60), "J =", heat(2.5,60)/4184, "kcal")
x = linspace(200,0)
ylin = heat(3, x)
plt.plot(x, ylin)
plt.title("Wykres ciepła liniowy")
plt.xlabel('V')
plt.ylabel('Q')
plt.legend('Wykres ciepła liniowy')
plt.gca().invert_xaxis()
plt.show()

ylog = heat(3, x)
plt.semilogy(x, ylog)
plt.title("Wykres ciepła logarytmiczny")
plt.xlabel('V')
plt.ylabel('Q')
plt.legend('Wykres ciepła logarytmiczny')
plt.gca().invert_xaxis()
plt.show()



cw.1
k = 3280.7316257200923 <class 'float'>
m = 4467 <class 'int'>
l = 2j <class 'complex'>
d = 7747.731625720093 <class 'float'>
c = (7747.731625720093+2j) <class 'complex'>

cw.2
d(3) = 7747.732
d(15) = 7747.731625720092779

cw.3
S = 5340.707511102648

cw.5
B = 0.5809230838528177

cw.6
M:
 [[ 1.41421356  1.         -1.41421356]
 [ 0.          1.          1.        ]
 [-1.41421356  1.41421356  1.        ]]
Minv:
 [[ 0.10355339  0.75       -0.60355339]
 [ 0.35355339  0.14644661  0.35355339]
 [-0.35355339  0.85355339 -0.35355339]]
Mt:
 [[ 1.41421356  0.         -1.41421356]
 [ 1.          1.          1.41421356]
 [-1.41421356  1.          1.        ]]
Mdet = -4.0

cw.7
 M(1,1) = 1.4142135623730951
M(3,3) = 1.0
M(3,2) = 1.4142135623730951
w1:
 [-1.41421356  1.          1.        ]
w2:
 [0. 1. 1.]

cw.8
Pierwiastki:  [ 5.  3.  2. -2. -1.]

Sprawdzenie wartosci [-8.952838470577262e-13, 0.0, -2.842170943040401e-14, 9.237055564881302e-14, 1.4210854715202004e-14]

cw.9
 [0.  0.5 1.  1.5 2.  2

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>


cw.11
Ciepło dla m=2.5kg, v=60km/h = 4500.0 J = 1.0755258126195029 kcal


<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>